# -*- coding: utf-8 -*-
"""medical_data_visualizer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDiZ7lIYUTrZxQwxdwi-zcC6hmBMgEJI
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('medical_examination.csv')

# 2. Tambahkan kolom overweight: BMI = weight / (height/100)^2
df['overweight'] = (df['weight'] / ((df['height'] / 100) ** 2) > 25).astype(int)

# 3. Normalisasi data: 0 = baik, 1 = buruk
df['cholesterol'] = (df['cholesterol'] > 1).astype(int)
df['gluc'] = (df['gluc'] > 1).astype(int)

def draw_cat_plot():
    # 4-5. Ubah data ke format long
    df_cat = pd.melt(df,
                     id_vars='cardio',
                     value_vars=['cholesterol', 'gluc', 'smoke', 'alco', 'active', 'overweight'])

    # 6. Buat dataframe baru untuk plotting
    df_cat = df_cat.groupby(['cardio', 'variable', 'value']).size().reset_index(name='total')

    # 7. Plot menggunakan seaborn.catplot
    fig = sns.catplot(data=df_cat, x='variable', y='total', hue='value', col='cardio', kind='bar').fig

    return fig

def draw_heat_map():
    # 8. Bersihkan data
    df_heat = df[
        (df['ap_lo'] <= df['ap_hi']) &
        (df['height'] >= df['height'].quantile(0.025)) &
        (df['height'] <= df['height'].quantile(0.975)) &
        (df['weight'] >= df['weight'].quantile(0.025)) &
        (df['weight'] <= df['weight'].quantile(0.975))
    ]

    # 9. Hitung korelasi
    corr = df_heat.corr()

    # 10. Buat mask segitiga atas
    mask = np.triu(np.ones_like(corr, dtype=bool))

    # 11-12. Buat heatmap
    fig, ax = plt.subplots(figsize=(12, 10))
    sns.heatmap(corr, mask=mask, annot=True, fmt=".1f", center=0, vmax=.3, vmin=-.1, square=True, linewidths=.5, cbar_kws={"shrink": .5})

    return fig